### ISSUE TITLE
How to download .dae file

### ISSUE THREAD

**Issue by NyeinEiEiTun** [eh3rrera/ARKitSceneKitExample#1]
Thanks for sharing this awesome code with us. I would like to replace with other 3D objects and playing around in this project but I could not download .dae file from this website https://sketchfab.com/models/38bbfc3454de4fe1b260d76f2e9f8b3d#.

**Comment by eh3rrera** [comment]
Thanks @NyeinEiEiTun!

Yes, that's a problem, not all 3D models are provided in DAE format. The most common format is OBJ with an additional file (MTL) for the textures, so what you can do is convert this OBJ/MTL file to DAE with a program like Blender.

The tutorial associated with this project guides you in the process of doing that. You can find it here:
https://blog.pusher.com/building-an-ar-app-with-arkit-and-scenekit/
(I just realized I didn't update it in the README, I'll do it)

Some models are easy to convert, others don't. I choose the cherub model for the project/tutorial because it presents some common issues. 

Take a look and let me know if it helps you.

**Comment by NyeinEiEiTun** [comment]
Thanks for sharing that nice tutorial. but I dun know which file should I download when I tap on the download button for old cherub vase. After downloading both files, I could not find the files with .obj and .mtl extensions.
<img width="503" alt="screen shot 2017-09-26 at 12 22 11 pm" src="https://user-images.githubusercontent.com/26161959/30842579-c61feb10-a2b5-11e7-847c-6e24ca50f9de.png">

**Comment by eh3rrera** [comment]
You should click on the OBJ option, it will download a ZIP file, unzip it, go to the source folder and unrar the file you'll find there: 
![screen shot 2017-09-26 at 08 50 13](https://user-images.githubusercontent.com/11665759/30863915-db5eb1a0-a297-11e7-84b7-b17c0411557b.png)
You should put the OBJ, MTL and JPG (the texture) files in the same directory and edit the paths of the OBJ and MTL files if necessary, as described in the article.

Take into account that not all free 3D models that are provided in OBJ have the MTL and JPG files, in other words, they are not uploaded correctly. In those cases, you could try other formats (if they are provided) or look for other model.

**Comment by NyeinEiEiTun** [comment]
@eh3rrera thanks so much for your replies. When I unzip the file, I can see 2 files called "source" and "textures". But When I open "source" file, I could only see the .rar file.
<img width="774" alt="screen shot 2017-09-26 at 10 07 07 pm" src="https://user-images.githubusercontent.com/26161959/30864840-6f457d44-a307-11e7-90d1-588c69a5cd34.png">

**Comment by eh3rrera** [comment]
Yes, unrar that file with a program like https://theunarchiver.com/, the OBJ and MTL files are inside (and the texture file is in "textures")

**Comment by NyeinEiEiTun** [comment]
Ohh!!! I can see them now.. many thanks. I can continue my Journey now. 👍
